---
version: 2
updates:
  # Maintain the pinned Rust toolchain
  - package-ecosystem: "rust-toolchain"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "Bump(rust): "
    cooldown:
      default-days: 7
