# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "cbc_decrypt",
    "cbc_encrypt",
    "cbc_verify",
    "sha512_crypt",
    "simple_7_decrypt",
    "simple_7_encrypt",
]

def cbc_decrypt(password: builtins.str, encrypted_data: builtins.str) -> builtins.str:
    r"""
    Decrypt the encrypted_data string using CBC TripleDES.
    
    Args:
        password: The encryption key.
        encrypted_data: The base64-encoded encrypted data to be decrypted.
    
    Returns:
        The decrypted data.
    
    Raises:
        ValueError: If encrypted_data is not valid base64 or decrypted data is not valid UTF-8.
        RuntimeError: If decryption fails.
    """

def cbc_encrypt(password: builtins.str, data: builtins.str) -> builtins.str:
    r"""
    Encrypt the data string using CBC TripleDES.
    
    Args:
        password: The encryption key.
        data: The data to be encrypted.
    
    Returns:
        The encrypted data, encoded in base64.
    
    Raises:
        RuntimeError: If encryption fails or base64 output contains invalid UTF-8.
    """

def cbc_verify(password: builtins.str, encrypted_data: builtins.str) -> builtins.bool:
    r"""
    Verify if an encrypted password is decryptable with the given key.
    
    It does not return the password but only raises an error if the password cannot be decrypted.
    
    Args:
        password: The decryption key.
        encrypted_data: The base64-encoded encrypted data to be decrypted.
    
    Returns:
        `True` if the password is decryptable, `False` otherwise.
    
    Raises:
        This function does not raise validation errors; invalid encrypted data returns `False`.
    """

def sha512_crypt(password: builtins.str, salt: builtins.str) -> builtins.str:
    r"""
    Computes the SHA512 crypt value for the password given the salt.
    
    The number of rounds is hardcoded to 5000 as expected by EOS.
    
    Args:
      password: The password.
      salt: The salt to use (truncated to 16 characters). Allowed characters are [a-zA-Z0-9/.].
    
    Returns:
      The sha512 crypt value.
    
    Raises:
      ValueError: If the salt is empty or contains invalid characters.
      RuntimeError: If the underlying SHA crypt library returns an error.
    """

def simple_7_decrypt(data: builtins.str) -> builtins.str:
    r"""
    Decrypt (deobfuscate) a password from insecure type-7.
    
    Raises ValueError if the password is empty or decryption fails.
    
    WARNING: Type-7 encryption is NOT secure and should only be used for compatibility
    with legacy systems. It provides only obfuscation, not real encryption.
    
    Args:
        data: The type-7 encrypted password to decrypt.
    
    Returns:
        The decrypted password.
    
    Raises:
        ValueError: If the password is empty or decryption fails.
        RuntimeError: If decrypted data is not valid UTF-8.
    """

def simple_7_encrypt(data: builtins.str, salt: typing.Optional[builtins.int]) -> builtins.str:
    r"""
    Encrypt (obfuscate) a password with insecure type-7.
    
    WARNING: Type-7 encryption is NOT secure and should only be used for compatibility
    with legacy systems. It provides only obfuscation, not real encryption.
    
    If salt is None, a random salt in the range 0-15 will be used.
    Raises ValueError if the password is empty or the salt is out of range.
    
    Args:
        data: The password to encrypt.
        salt: The salt value (0-15). If None, a random salt will be generated.
    
    Returns:
        The encrypted password in type-7 format.
    
    Raises:
        ValueError: If the password is empty or the salt is out of range.
        RuntimeError: If the random salt source is unavailable or encrypted data is not valid UTF-8.
    """

