# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import os
import pathlib
import typing
__all__ = [
    "Configuration",
    "Deprecation",
    "IgnoredEosConfigKey",
    "ValidatedDataResult",
    "ValidationResult",
    "Violation",
    "get_validated_data",
    "init_store_from_file",
    "validate_json",
    "validate_json_with_adhoc_schema",
]

class Configuration:
    r"""
    Configuration for validation behavior.
    """
    ignore_required_keys_on_root_dict: builtins.bool
    r"""
    Ignore required keys on the root dictionary.
    """
    return_coercion_infos: builtins.bool
    r"""
    Return coercion information in the validation result.
    """
    restrict_null_values: builtins.bool
    r"""
    Emit type errors for Null values instead of ignoring them.
    """
    warn_eos_config_keys: builtins.bool
    r"""
    When validating avd_design, emit warnings for top-level keys that exist in eos_config but not in avd_design.
    """
    def __init__(self, *, ignore_required_keys_on_root_dict: builtins.bool = False, return_coercion_infos: builtins.bool = False, restrict_null_values: builtins.bool = False, warn_eos_config_keys: builtins.bool = False) -> None: ...

class Deprecation:
    r"""
    Input data model is deprecated.
    """
    message: builtins.str
    r"""
    String detailing the deprecation.
    """
    path: builtins.list[builtins.str]
    r"""
    Path to the data which uses a deprecated data model.
    """
    removed: builtins.bool
    r"""
    True when the data model is removed.
    """
    version: typing.Optional[builtins.str]
    r"""
    Version where the model will be removed.
    """
    replacement: typing.Optional[builtins.str]
    r"""
    New data model to use instead.
    """
    url: typing.Optional[builtins.str]
    r"""
    Url where more information can be found.
    """

class IgnoredEosConfigKey:
    r"""
    EOS Config key found in AVD Design input.
    """
    message: builtins.str
    r"""
    String detailing the ignored key.
    """
    path: builtins.list[builtins.str]
    r"""
    Path to the ignored key.
    """

class ValidatedDataResult:
    r"""
    Result of data validation including the validated data as JSON.
    """
    validation_result: ValidationResult
    validated_data: typing.Optional[builtins.str]

class ValidationResult:
    r"""
    Result of data validation.
    """
    violations: builtins.list[Violation]
    deprecations: builtins.list[Deprecation]
    ignored_eos_config_keys: builtins.list[IgnoredEosConfigKey]

class Violation:
    r"""
    Input data violates the schema.
    """
    message: builtins.str
    r"""
    String detailing the violation.
    """
    path: builtins.list[builtins.str]
    r"""
    Path to the data which the violation concerns.
    """

def get_validated_data(data_as_json: str, schema_name: typing.Literal["eos_config", "avd_design", "cv_deploy"], configuration: Configuration | None = None) -> ValidatedDataResult:
    r"""
    Validate data against a schema specified by name and return the data after coercion and validation.
    
    This returned data is the type-coerced data encoded as JSON, which also contains default values that got inserted during validation.
    
    Raises:
        RuntimeError: If the schema store is not initialized, schema_name is invalid, input data is invalid JSON, coerced data cannot be serialized as JSON, or validation reports an internal error.
    """

def init_store_from_file(file: builtins.str | os.PathLike | pathlib.Path) -> None:
    r"""
    Initialize the Schema store from a file containing the full schema store.
    
    Usually this is the schema.json.gz file built with pyavd.
    This must be called before running any validations, since the store is a write-once static.
    
    Raises:
        RuntimeError: If the schema store cannot be loaded, resolved, or is already initialized.
    """

def validate_json(data_as_json: str, schema_name: typing.Literal["eos_config", "avd_design", "cv_deploy"], configuration: Configuration | None = None) -> ValidationResult:
    r"""
    Validate data against a schema specified by name.
    
    Raises:
        RuntimeError: If the schema store is not initialized, schema_name is invalid, input data is invalid JSON, or validation reports an internal error.
    """

def validate_json_with_adhoc_schema(data_as_json: builtins.str, schema_as_json: builtins.str, configuration: typing.Optional[Configuration] = None) -> ValidationResult:
    r"""
    Validate data against the given schema.
    
    Raises:
        RuntimeError: If the schema store is not initialized, data_as_json or schema_as_json is invalid JSON, or validation reports an internal error.
    """

