---
name: "Build and Test Pull Request and main branch"

"on":
  pull_request:

  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  # For PRs the head_ref will be used. For Merge Queues (merge_group) we fallback to run_id.
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  # Augment verbosity if ACTIONS_STEP_DEBUG is set
  CIBW_BUILD_VERBOSITY: ${{ secrets.ACTIONS_STEP_DEBUG && 3 || 0 }}
  # TODO: Check if this is used for pytest
  PY_COLORS: 1
  # rust
  CARGO_TERM_COLOR: always

jobs:
  python_coverage:
    name: Python coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3.11
      - name: Install tox
        run: |
          pip install tox --upgrade
      - name: Generate coverage report
        run: |-
          tox run -e coverage,report
      - name: Upload pytest coverage data
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: pytest-coverage
          path: coverage.xml

  # ----------------------------------- #
  # Cargo build, test and linting
  # ----------------------------------- #
  cargo_build_and_test:
    name: Cargo build, test and linting on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - windows-latest
          - macos-15-intel
          - macos-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Install Rust toolchain from rust-toolchain.toml
        run: rustup show
      # This is needed because we have pyo3 tests and our minimum python version is 3.10.
      # On some test containers (looking at you windows-latest) the included Python is 3.9.
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.12"
      - name: Install YAML test suite fixture
        run: python scripts/fetch_yaml_test_suite.py
      - name: Run all tests
        run: cargo test --locked --all-targets --all-features
      - name: Generate coverage report with cargo llvm-cov
        run: |
          cargo install cargo-llvm-cov --locked
          cargo llvm-cov --locked --all-targets --all-features --lcov --output-path lcov.info
        if: |
          matrix.os == 'ubuntu-latest'
      - name: Upload coverage report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: rust-llvm-cov
          path: lcov.info
        if: |
          matrix.os == 'ubuntu-latest'
      - name: Test building to all targets
        run: cargo build --locked --all-targets --all-features

  codecov:
    name: Upload coverage to CodeCov
    needs: [python_coverage, cargo_build_and_test]
    if: github.repository == 'aristanetworks/pyavd-utils'
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/codecov.yml

  # --------------------------------------------------------------------- #
  # Build and test cross platform pyavd-utils wheels and upload artifacts
  # --------------------------------------------------------------------- #
  build_and_test_pyavd_utils_wheels:
    name: Build pyavd-utils wheel on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - windows-latest
          - macos-15-intel
          - macos-latest
    uses: ./.github/workflows/build-wheel.yml
    with:
      runner: ${{ matrix.os }}
